FROM cgr.dev/chainguard/wolfi-base as build

RUN apk update && apk add openjdk-17 maven~3.9

WORKDIR /app
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk

COPY .mvn/ .mvn
COPY mvnw pom.xml ./
COPY src ./src
RUN ./mvnw package

FROM cgr.dev/chainguard/wolfi-base

RUN apk update && apk add openjdk-17-default-jvm

# Some Java apps may require extra locale files
# RUN apk add glibc-locale-en

USER nonroot

COPY --from=build /app/target/spring-petclinic-3.1.0-SNAPSHOT.jar /

ENTRYPOINT ["java", "-jar", "/spring-petclinic-3.1.0-SNAPSHOT.jar"]
